const SIGN_IN = "SIGN_IN";
const SIGN_OUT = "SIGN_OUT";
const SIGN_UP = "SIGN_UP";
const GET_LESSONS = "GET_LESSONS";
const GET_MY_LESSONS = "GET_MY_LESSONS";
const GET_MY_COURSES_PROGRESS = "GET_MY_COURSES_PROGRESS";
const GET_LESSON = "GET_LESSON";
const GET_LESSON_BY_ID = "GET_LESSON_BY_ID";

export {
  SIGN_IN,
  SIGN_OUT,
  SIGN_UP,
  GET_LESSONS,
  GET_MY_LESSONS,
  GET_LESSON,
  GET_LESSON_BY_ID,
  GET_MY_COURSES_PROGRESS,
};
